"""add is_active and created_at to user

Revision ID: e85c20c3ae68
Revises: 8cd45c4f3b1b
Create Date: 2026-01-02 16:31:09.585814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85c20c3ae68'
down_revision: Union[str, Sequence[str], None] = '8cd45c4f3b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults so existing rows get valid values
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    )
    op.add_column(
        'users',
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'))
    )
    # Remove server defaults to rely on SQLAlchemy defaults going forward
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
